program VIS_LAGER;


uses
  Forms,
  fMain in 'fMain.pas' {frmMain},
  VidaConst in 'VidaConst.pas',
  frmLogon in 'frmLogon.pas' {dlgLogOn},
  frmDBAdmin in 'frmDBAdmin.pas' {dlgDBAdmin},
  uEncode in 'uEncode.pas',
  dmsVidaSystem in 'dmsVidaSystem.pas' {dmsSystem: TDataModule},
  dmcVidaSystem in 'dmcVidaSystem.pas' {dmcSystem: TDataModule},
  VidaType in 'VidaType.pas',
  fDBForm in 'fDBForm.pas' {frmDBForm},
  UnitCRViewReport in 'UnitCRViewReport.pas' {FormCRViewReport},
  dmBooking in 'dmBooking.pas' {dm_Booking: TDataModule},
  UnitCarrier in 'UnitCarrier.pas' {FormCarrier},
  dmcVidaPayment in 'dmcVidaPayment.pas' {dmcPayment: TDataModule},
  UnitPkgInfo in 'UnitPkgInfo.pas' {frmPkgInfo},
  UnitPkgNo in 'UnitPkgNo.pas' {frmPkgNo},
  UnitInventoryReport in 'UnitInventoryReport.pas' {frmInventoryReport},
  dm_Inventory in 'dm_Inventory.pas' {dmInventory: TDataModule},
  dmsVidaPkg in 'dmsVidaPkg.pas' {dmsPkg: TDataModule},
  dmcPkgs in 'dmcPkgs.pas' {dmPkgs: TDataModule},
  UnitLONumber in 'UnitLONumber.pas' {fLONumber},
  UnitCRPrintReport in 'UnitCRPrintReport.pas' {FormCRPrintReport},
  uStickyNote in 'uStickyNote.pas' {frmStickyNote},
  dlgPickPkg_II in 'dlgPickPkg_II.pas' {frmPackagePicker_II},
  uEntryField in 'uEntryField.pas' {fEntryField},
  uProductionUnit in 'uProductionUnit.pas' {frmProductionUnit},
  uBasMatPunkter in 'uBasMatPunkter.pas' {fBasMatPunkter},
  uPktNrPos in 'uPktNrPos.pas' {fPktNrPos},
  UPkgNoPos in 'UPkgNoPos.pas' {fPkgNoPos},
  uInvCtrl in 'uInvCtrl.pas' {fInvCtrl},
  dmcInvCtrl in 'dmcInvCtrl.pas' {dmInvCtrl: TDataModule},
  dlgPickPkg_III in 'dlgPickPkg_III.pas' {frmPackagePicker_III},
  uPickPkgNo in 'uPickPkgNo.pas' {fPickPkgNo},
  uConfirmCodeDialog in 'uConfirmCodeDialog.pas' {frmConfirmCodeDialog},
  uInvCtrlList in 'uInvCtrlList.pas' {fInvCtrlList},
  uSelectShipper in 'uSelectShipper.pas' {fSelectShipper},
  uGridSetting in 'uGridSetting.pas' {fGridSetting},
  dmsSinglePkg in 'dmsSinglePkg.pas' {dm_SinglePkg: TDataModule},
  uSinglePkgEntry in 'uSinglePkgEntry.pas' {fSinglePkgEntry},
  dmcLoadPlan in 'dmcLoadPlan.pas' {dmLoadPlan: TDataModule},
  uSelectLoadPlan in 'uSelectLoadPlan.pas' {fSelectLoadPlan},
  uInventeraPIG in 'uInventeraPIG.pas' {fInventeraPIG},
  uSelectLIP in 'uSelectLIP.pas' {fSelectLIP},
  uPigNames in 'uPigNames.pas' {fPigNames},
  uSelectInvPIG in 'uSelectInvPIG.pas' {fSelectInvPIG},
  uDistDupPkgsToLoadPlan in 'uDistDupPkgsToLoadPlan.pas' {fDistDupPkgsToLoadPlan},
  uAOUser in 'uAOUser.pas' {fAOUser},
  dmcVidaOrder in 'dmcVidaOrder.pas' {dmcOrder: TDataModule},
  uAnalyseraLeveranser in 'uAnalyseraLeveranser.pas' {fAnalyseraLeveranser},
  uSendMapiMail in 'uSendMapiMail.pas' {dm_SendMapiMail: TDataModule},
  UnitPkgEntry in 'UnitPkgEntry.pas' {frmPkgEntry},
  dmsVidaContact in 'dmsVidaContact.pas' {dmsContact: TDataModule},
  dmcProduct in 'dmcProduct.pas' {dmProduct: TDataModule},
  dmsDataConn in 'dmsDataConn.pas' {dmsConnector: TDataModule},
  UnitRemovePkg in 'UnitRemovePkg.pas' {frmRemovePkg},
  dmc_UserProps in 'dmc_UserProps.pas' {dm_UserProps: TDataModule},
  UfelRegPkg in 'UfelRegPkg.pas' {ffelRegPkg},
  UnitMovePkgs in 'UnitMovePkgs.pas' {frmMovePkgs},
  dmc_DryKiln in 'dmc_DryKiln.pas' {dm_DryKiln: TDataModule},
  uKilnProps in 'uKilnProps.pas' {fKilnProps},
  uKilnCharges in 'uKilnCharges.pas' {fKilnCharges},
  uKilnChargeNote in 'uKilnChargeNote.pas' {fKilnChargeNote},
  uScanPkgNo in 'uScanPkgNo.pas' {fScanPkgNo},
  uKilnWizard in 'uKilnWizard.pas' {fKilnWizard},
  uSIC in 'uSIC.pas' {fSIC},
  uSicICgrp in 'uSicICgrp.pas' {fSicICgrp},
  uModifySIC in 'uModifySIC.pas' {fModifySIC},
  uLipForSic in 'uLipForSic.pas' {fLipForSic},
  UnitAboutBox in '..\..\CommonUnits\UnitAboutBox.pas' {AboutBox},
  uInvCare in 'uInvCare.pas' {fuInvCare},
  uChangeLogins in 'uChangeLogins.pas' {OKHelpBottomDlg},
  uVardaBortPkt in 'uVardaBortPkt.pas' {fVardaBortPkt},
  uchgPkgVard in 'uchgPkgVard.pas' {fchgPkgVard},
  VidaUtils in 'VidaUtils.pas',
  uAddSpecialLengths in 'uAddSpecialLengths.pas' {fAddSpecialLengths},
  uMemoForm in 'uMemoForm.pas' {fMemoForm},
  uSokAvropMall in 'uSokAvropMall.pas' {fSokAvropMall},
  uInvLogs in 'uInvLogs.pas' {fInvLogs},
  uPriceListInventory in 'uPriceListInventory.pas' {fPriceListInventory},
  uGenInvCountForAll in 'uGenInvCountForAll.pas' {fGenInvCountForAll},
  uInvCreateManyCtrlList in 'uInvCreateManyCtrlList.pas' {fInvCreateManyCtrlList},
  uCreateSicPriceGroups in 'uCreateSicPriceGroups.pas' {fCreateSicPriceGroups},
  uSicPriceGroup in 'uSicPriceGroup.pas' {fSicPriceGroup},
  dmc_ArrivingLoads in 'dmc_ArrivingLoads.pas' {dmArrivingLoads: TDataModule},
  UnitLoadArrivals in 'UnitLoadArrivals.pas' {frmLoadArrivals},
  uAnkomstRegProgress in 'uAnkomstRegProgress.pas' {fAnkomstRegProgress},
  UnitCRPrintOneReport in 'UnitCRPrintOneReport.pas' {FormCRPrintOneReport},
  uAccInv in 'uAccInv.pas' {fAccInv},
  uAccParams in 'uAccParams.pas' {fAccParams},
  uEntryPriceField in 'uEntryPriceField.pas' {fEntryPriceField},
  UnitGetProd_II in 'UnitGetProd_II.pas' {frmGetProd_II},
  uExtAterstall in 'uExtAterstall.pas' {fExtAterstall},
  PackageImportU in 'ImportLoad\PackageImportU.pas',
  PackageExportU in 'ImportLoad\PackageExportU.pas',
  DeliveryMessageWoodV2R31 in 'ImportLoad\DeliveryMessageWoodV2R31.pas',
  dmsVidaProduct in 'dmsVidaProduct.pas' {dmsProduct: TDataModule},
  VidaUser in '..\..\CommonUnits\VidaUser.pas',
  UProductionReport in 'UProductionReport.pas' {fProductionReport},
  uInventeringsRapport in 'uInventeringsRapport.pas' {fInventeringsRapport},
  uAngeNyMall in 'uAngeNyMall.pas' {fAngeNyMall},
  uDeliveryReport in 'uDeliveryReport.pas' {fDeliveryReport},
  uUserProfiles in 'uUserProfiles.pas' {fUserProfiles},
  VidaDeliveryClass in 'VidaDeliveryClass.pas',
  uSimulateHandHeld in 'uSimulateHandHeld.pas' {fSimulateHandHeld},
  WorkMinutesU in 'WorkMinutesU.pas',
  uEnterFieldValue in 'uEnterFieldValue.pas' {fEnterFieldValue},
  uStopptidReport in 'uStopptidReport.pas' {fStopptidReport},
  fLoadPlan in 'fLoadPlan.pas' {frmLoadPlan},
  uSelectPkgTypes in 'uSelectPkgTypes.pas' {fSelectPkgTypes},
  uKilnHandling in 'uKilnHandling.pas' {fkilnHandling},
  uEnterKilnVagn in 'uEnterKilnVagn.pas' {fEnterKilnVagn},
  uPickPkgNoTork in 'uPickPkgNoTork.pas' {fPickPkgNoTork},
  uPackageCostPerPkg in 'uPackageCostPerPkg.pas' {fPackageCostPerPkg},
  uSetMall in 'uSetMall.pas' {fSetMall},
  PrintUnit in 'PrintUnit.pas',
  CR_Plugin_Import in 'CR_Plugin_Import.pas',
  uLagerBalans in 'uLagerBalans.pas' {fLagerBalans},
  uLagBalDtl in 'uLagBalDtl.pas' {fLagBalDtl};

{$R *.res}
begin
  Application.Initialize;
  Application.Title := 'VISLAGER';
  Application.HelpFile := 'D:\Project\VIS\Help manual\VIS.hlp';
  Application.CreateForm(TFrmMain, FrmMain);
  Application.CreateForm(TdmsConnector, dmsConnector);
  Application.CreateForm(TdmsSystem, dmsSystem);
  Application.CreateForm(TdmcSystem, dmcSystem);
  Application.CreateForm(TdmLoadPlan, dmLoadPlan);
  Application.CreateForm(TdmcOrder, dmcOrder);
  Application.CreateForm(TdmsContact, dmsContact);
  Application.CreateForm(TdmInventory, dmInventory);
  Application.Run
end.
